use crate::config::MudMakerConfig;
use maker_common::content::ContentDir;
use maker_common::process::{HasProcessManager, ProcessManager};
use maker_common::scripts::ScriptsDir;
use std::path::PathBuf;
use std::sync::Arc;

/// Shared application state for MUD Game Maker.
#[derive(Clone)]
pub struct AppState {
    pub config: Arc<MudMakerConfig>,
    pub process: ProcessManager,
}

impl AppState {
    pub fn new(config: MudMakerConfig) -> Self {
        let process = ProcessManager::new(
            "project_mud",
            PathBuf::from(&config.project.mud_config),
            vec![],
        );
        Self {
            config: Arc::new(config),
            process,
        }
    }
}

impl ContentDir for AppState {
    fn content_dir(&self) -> PathBuf {
        self.config.content_dir()
    }
}

impl ScriptsDir for AppState {
    fn scripts_dir(&self) -> PathBuf {
        self.config.scripts_dir()
    }

    fn excluded_scripts(&self) -> Vec<String> {
        // 01_world_setup.lua is auto-generated by the maker
        vec!["01_world_setup.lua".to_string(), "05_triggers.lua".to_string()]
    }
}

impl HasProcessManager for AppState {
    fn process_manager(&self) -> &ProcessManager {
        &self.process
    }
}

impl AppState {
    /// Get the MUD server telnet address for the preview proxy.
    pub fn telnet_addr(&self) -> String {
        self.config.project.telnet_addr.clone()
    }
}
