-- 05_triggers.lua (auto-generated by MUD Game Maker)
-- DO NOT EDIT MANUALLY — changes will be overwritten

-- Room entry triggers
hooks.on_enter_room(function(entity, room, old_room)
    local room_name = ecs:get(room, "Name") or ""
    if room_name == "어두운 동굴" then -- 어두운 동굴 경고
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "어둠 속으로 들어서자 등골이 오싹해집니다. 깊은 곳에서 희미한 긁는 소리가 울려 퍼집니다...") end
    end
    if room_name == "고블린 야영지" then -- 고블린 야영지 매복
        output:broadcast_room(room, "고블린들이 경계의 비명을 지릅니다! 무기를 움켜쥐고 전투 태세를 갖춥니다!")
    end
end)

-- Trigger: 분수대에서 기도
hooks.on_action("pray", function(ctx)
    local sid = sessions:session_for(entity)
    if sid then output:send(sid, "고대의 분수대 앞에 무릎을 꿇고 기도합니다. 따뜻한 빛이 감싸며 상처가 치유되기 시작합니다.") end
    ecs:set(entity, "Health", "{current = 100, max = 100}")
    return true
end)

-- Tick-based triggers
hooks.on_tick(function(tick)
    if tick % 600 == 0 then -- 고블린 리스폰 타이머
        local spawned_goblin = ecs:spawn()
        ecs:set(spawned_goblin, "Name", "고블린")
        ecs:set(spawned_goblin, "NpcTag", true)
        ecs:set(spawned_goblin, "Health", {current = 30, max = 30})
        ecs:set(spawned_goblin, "Attack", 5)
        ecs:set(spawned_goblin, "Defense", 2)
        local target_room = nil
        for _, r in ipairs(space:all_rooms()) do
            if ecs:get(r, "Name") == "고블린 야영지" then target_room = r break end
        end
        if target_room then space:place_entity(spawned_goblin, target_room) end
    end
    -- Death trigger: 고블린 족장 처치 보상
    local dead_entities = ecs:query("Dead")
    for _, dead_ent in ipairs(dead_entities) do
        local name = ecs:get(dead_ent, "Name") or ""
        if name == "고블린 족장" then
            output:broadcast_room(room, "고블린 족장이 쓰러집니다! 반짝이는 왕관이 바닥을 굴러갑니다.")
            local spawned_goblin_crown = ecs:spawn()
            ecs:set(spawned_goblin_crown, "Name", "고블린 왕관")
            ecs:set(spawned_goblin_crown, "ItemTag", true)
            local target_room = nil
            for _, r in ipairs(space:all_rooms()) do
                if ecs:get(r, "Name") == "고블린 야영지" then target_room = r break end
            end
            if target_room then space:place_entity(spawned_goblin_crown, target_room) end
        end
    end
end)

-- Connection triggers
hooks.on_connect(function(session_id)
    -- 신규 플레이어 환영
    local sid = sessions:session_for(entity)
    if sid then output:send(sid, "엘도리아 마을에 오신 것을 환영합니다! '도움말'을 입력하면 명령어 목록을 볼 수 있습니다. 마을을 탐험하고, 몬스터와 싸우고, 보물을 발견하세요!") end
    local item_healing_potion = ecs:spawn()
    ecs:set(item_healing_potion, "Name", "치유 물약")
    ecs:set(item_healing_potion, "ItemTag", true)
    ecs:set(item_healing_potion, "Inventory", entity)
end)
