-- 08_item_effects.lua (auto-generated by MUD Game Maker)
-- DO NOT EDIT MANUALLY -- changes will be overwritten

local ITEM_DATA = {
    ["녹슨 검"] = { item_type = "weapon", heal_amount = 0, attack_bonus = 3, defense_bonus = 0, use_message = "", equip_slot = "" },
    ["철 검"] = { item_type = "weapon", heal_amount = 0, attack_bonus = 8, defense_bonus = 0, use_message = "", equip_slot = "" },
    ["치유 물약"] = { item_type = "consumable", heal_amount = 30, attack_bonus = 0, defense_bonus = 0, use_message = "", equip_slot = "" },
    ["암흑 로브"] = { item_type = "armor", heal_amount = 0, attack_bonus = 0, defense_bonus = 5, use_message = "", equip_slot = "" },
}

local function find_inventory_item(entity, item_name)
    local inv = ecs:get(entity, "Inventory")
    if not inv or not inv.items then return nil end
    for _, item_id in ipairs(inv.items) do
        if ecs:get(item_id, "Name") == item_name then return item_id end
    end
    return nil
end

local function remove_from_inventory(entity, item_ent)
    local inv = ecs:get(entity, "Inventory")
    if not inv or not inv.items then return end
    local new_items = {}
    local removed = false
    for _, id in ipairs(inv.items) do
        if id == item_ent and not removed then
            removed = true
        else
            table.insert(new_items, id)
        end
    end
    ecs:set(entity, "Inventory", {items = new_items})
end

-- Use consumable items
hooks.on_action("use", function(ctx)
    local entity = ctx.entity
    local item_name = ctx.args
    if not item_name or item_name == "" then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "사용할 아이템을 지정하세요: use <아이템>") end
        return true
    end
    local item_ent = find_inventory_item(entity, item_name)
    if not item_ent then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "'" .. item_name .. "'을(를) 가지고 있지 않습니다.") end
        return true
    end
    local data = ITEM_DATA[item_name]
    if not data or data.item_type ~= "consumable" then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "'" .. item_name .. "'은(는) 사용할 수 없습니다.") end
        return true
    end
    -- Apply heal
    if data.heal_amount > 0 then
        local hp = ecs:get(entity, "Health")
        if hp then
            hp.current = math.min(hp.current + data.heal_amount, hp.max)
            ecs:set(entity, "Health", hp)
        end
    end
    -- Remove item
    remove_from_inventory(entity, item_ent)
    ecs:despawn(item_ent)
    local sid = sessions:session_for(entity)
    if sid then
        local msg = data.use_message ~= "" and data.use_message or (item_name .. "을(를) 사용했습니다.")
        output:send(sid, msg)
    end
    return true
end)

-- Equip items
hooks.on_action("equip", function(ctx)
    local entity = ctx.entity
    local item_name = ctx.args
    if not item_name or item_name == "" then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "장착할 아이템을 지정하세요: equip <아이템>") end
        return true
    end
    local item_ent = find_inventory_item(entity, item_name)
    if not item_ent then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "'" .. item_name .. "'을(를) 가지고 있지 않습니다.") end
        return true
    end
    local data = ITEM_DATA[item_name]
    if not data or (data.item_type ~= "weapon" and data.item_type ~= "armor") then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "'" .. item_name .. "'은(는) 장착할 수 없습니다.") end
        return true
    end
    -- Apply bonuses
    if data.attack_bonus > 0 then
        local atk = ecs:get(entity, "Attack") or 0
        ecs:set(entity, "Attack", atk + data.attack_bonus)
    end
    if data.defense_bonus > 0 then
        local def = ecs:get(entity, "Defense") or 0
        ecs:set(entity, "Defense", def + data.defense_bonus)
    end
    local sid = sessions:session_for(entity)
    if sid then output:send(sid, item_name .. "을(를) 장착했습니다.") end
    return true
end)

-- Unequip items
hooks.on_action("unequip", function(ctx)
    local entity = ctx.entity
    local item_name = ctx.args
    if not item_name or item_name == "" then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "해제할 아이템을 지정하세요: unequip <아이템>") end
        return true
    end
    local item_ent = find_inventory_item(entity, item_name)
    if not item_ent then
        local sid = sessions:session_for(entity)
        if sid then output:send(sid, "'" .. item_name .. "'을(를) 가지고 있지 않습니다.") end
        return true
    end
    local data = ITEM_DATA[item_name]
    if not data then return true end
    -- Remove bonuses
    if data.attack_bonus > 0 then
        local atk = ecs:get(entity, "Attack") or 0
        ecs:set(entity, "Attack", math.max(0, atk - data.attack_bonus))
    end
    if data.defense_bonus > 0 then
        local def = ecs:get(entity, "Defense") or 0
        ecs:set(entity, "Defense", math.max(0, def - data.defense_bonus))
    end
    local sid = sessions:session_for(entity)
    if sid then output:send(sid, item_name .. "을(를) 해제했습니다.") end
    return true
end)
