-- 09_shops.lua (auto-generated by MUD Game Maker)
-- DO NOT EDIT MANUALLY -- changes will be overwritten

local SHOPS = {
    ["상인 아저씨"] = {
        name = "마을 잡화점",
        room = "마을 광장",
        sell_rate = 0.5,
        items = {
            { name = "healing_potion", price = 20 },
            { name = "rusty_sword", price = 50 },
        },
    },
}

local function find_shop_in_room(entity)
    local room = space:entity_room(entity)
    if not room then return nil end
    local occupants = space:room_occupants(room)
    for _, occ in ipairs(occupants) do
        if ecs:has(occ, "NpcTag") then
            local npc_name = ecs:get(occ, "Name") or ""
            if SHOPS[npc_name] then return SHOPS[npc_name], npc_name end
        end
    end
    return nil
end

hooks.on_action("shop", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return true end
    local shop, npc_name = find_shop_in_room(entity)
    if not shop then
        output:send(sid, "이 근처에 상점이 없습니다.")
        return true
    end
    output:send(sid, colors.yellow .. "=== " .. shop.name .. " (" .. npc_name .. ") ===" .. colors.reset)
    for i, item in ipairs(shop.items) do
        output:send(sid, string.format("  %d. %s - %d 골드", i, item.name, item.price))
    end
    output:send(sid, colors.cyan .. "구매: buy <아이템> | 판매: sell <아이템>" .. colors.reset)
    return true
end)

hooks.on_action("buy", function(ctx)
    local entity = ctx.entity
    local item_name = ctx.args
    local sid = sessions:session_for(entity)
    if not sid then return true end
    if not item_name or item_name == "" then
        output:send(sid, "구매할 아이템을 지정하세요: buy <아이템>")
        return true
    end
    local shop = find_shop_in_room(entity)
    if not shop then
        output:send(sid, "이 근처에 상점이 없습니다.")
        return true
    end
    local shop_item = nil
    for _, si in ipairs(shop.items) do
        if si.name == item_name then shop_item = si break end
    end
    if not shop_item then
        output:send(sid, "'" .. item_name .. "'은(는) 이 상점에서 판매하지 않습니다.")
        return true
    end
    local gold = ecs:get(entity, "Gold") or 0
    if gold < shop_item.price then
        output:send(sid, "골드가 부족합니다. (보유: " .. gold .. ", 필요: " .. shop_item.price .. ")")
        return true
    end
    -- Deduct gold
    ecs:set(entity, "Gold", gold - shop_item.price)
    -- Create item entity
    local new_item = ecs:spawn()
    ecs:set(new_item, "Name", shop_item.name)
    ecs:set(new_item, "ItemTag", true)
    ecs:set(new_item, "Inventory", entity)
    output:send(sid, shop_item.name .. "을(를) 구매했습니다. (-" .. shop_item.price .. " 골드)")
    return true
end)

hooks.on_action("sell", function(ctx)
    local entity = ctx.entity
    local item_name = ctx.args
    local sid = sessions:session_for(entity)
    if not sid then return true end
    if not item_name or item_name == "" then
        output:send(sid, "판매할 아이템을 지정하세요: sell <아이템>")
        return true
    end
    local shop = find_shop_in_room(entity)
    if not shop then
        output:send(sid, "이 근처에 상점이 없습니다.")
        return true
    end
    -- Find item in inventory
    local inv = ecs:get(entity, "Inventory")
    if not inv or not inv.items then
        output:send(sid, "인벤토리가 비어 있습니다.")
        return true
    end
    local item_ent = nil
    for _, id in ipairs(inv.items) do
        if ecs:get(id, "Name") == item_name then item_ent = id break end
    end
    if not item_ent then
        output:send(sid, "'" .. item_name .. "'을(를) 가지고 있지 않습니다.")
        return true
    end
    -- Find sell price from shop items or use base value
    local sell_price = 0
    for _, si in ipairs(shop.items) do
        if si.name == item_name then
            sell_price = math.floor(si.price * shop.sell_rate)
            break
        end
    end
    if sell_price <= 0 then sell_price = 1 end
    -- Remove item from inventory
    local new_items = {}
    local removed = false
    for _, id in ipairs(inv.items) do
        if id == item_ent and not removed then removed = true
        else table.insert(new_items, id) end
    end
    ecs:set(entity, "Inventory", {items = new_items})
    ecs:despawn(item_ent)
    -- Add gold
    local gold = ecs:get(entity, "Gold") or 0
    ecs:set(entity, "Gold", gold + sell_price)
    output:send(sid, item_name .. "을(를) 판매했습니다. (+" .. sell_price .. " 골드)")
    return true
end)
