-- 10_dialogues.lua (auto-generated by MUD Game Maker)
-- DO NOT EDIT MANUALLY -- changes will be overwritten

local DIALOGUES = {
    ["경비병"] = {
        id = "guard_dialogue",
        nodes = {
            ["start"] = {
                text = "멈춰라! 무슨 용무인가?",
                choices = {
                    { text = "고블린에 대해 물어본다", next = "goblin_info", action = nil },
                    { text = "그냥 지나간다", next = nil, action = nil },
                },
            },
            ["goblin_info"] = {
                text = "최근 고블린이 마을 근처까지 내려왔다. 처치해줄 수 있나?",
                choices = {
                    { text = "도와드리겠습니다", next = nil, action = "start_quest:goblin_hunt" },
                    { text = "생각해보겠습니다", next = nil, action = nil },
                },
            },
        },
    },
}

local dialogue_states = {}

local function show_dialogue_node(entity, sid, npc_name, node_id)
    local dlg = DIALOGUES[npc_name]
    if not dlg then return false end
    local node = dlg.nodes[node_id]
    if not node then
        dialogue_states[entity] = nil
        return false
    end
    output:send(sid, "")
    output:send(sid, colors.yellow .. npc_name .. colors.reset .. ": " .. node.text)
    if #node.choices > 0 then
        for i, choice in ipairs(node.choices) do
            output:send(sid, colors.cyan .. "  " .. i .. ". " .. choice.text .. colors.reset)
        end
        dialogue_states[entity] = {npc_name = npc_name, node_id = node_id}
    else
        dialogue_states[entity] = nil
    end
    return true
end

local function execute_action(entity, sid, action_str)
    if not action_str then return end
    local cmd, arg = action_str:match("^(%w+):(.+)$")
    if not cmd then return end
    if cmd == "give_item" then
        local item = ecs:spawn()
        ecs:set(item, "Name", arg)
        ecs:set(item, "ItemTag", true)
        ecs:set(item, "Inventory", entity)
        output:send(sid, colors.green .. arg .. "을(를) 받았습니다." .. colors.reset)
    elseif cmd == "give_gold" then
        local amount = tonumber(arg) or 0
        local gold = ecs:get(entity, "Gold") or 0
        ecs:set(entity, "Gold", gold + amount)
        output:send(sid, colors.green .. amount .. " 골드를 받았습니다." .. colors.reset)
    elseif cmd == "heal" then
        local hp = ecs:get(entity, "Health")
        if hp then
            hp.current = hp.max
            ecs:set(entity, "Health", hp)
            output:send(sid, colors.green .. "체력이 완전히 회복되었습니다." .. colors.reset)
        end
    elseif cmd == "start_quest" then
        -- Quest integration: set QuestLog component
        local quest_log = ecs:get(entity, "QuestLog") or {active = {}, completed = {}}
        if not quest_log.active[arg] and not quest_log.completed[arg] then
            quest_log.active[arg] = {}
            ecs:set(entity, "QuestLog", quest_log)
            output:send(sid, colors.green .. "퀘스트 '" .. arg .. "'을(를) 수락했습니다." .. colors.reset)
        end
    end
end

hooks.on_action("talk", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return true end
    local target_name = ctx.args
    local room = space:entity_room(entity)
    if not room then return true end
    -- Find NPC in room
    local npc_name = nil
    local occupants = space:room_occupants(room)
    for _, occ in ipairs(occupants) do
        if ecs:has(occ, "NpcTag") then
            local name = ecs:get(occ, "Name") or ""
            if target_name == "" or target_name == nil or name == target_name then
                if DIALOGUES[name] then
                    npc_name = name
                    break
                end
            end
        end
    end
    if not npc_name then
        output:send(sid, "대화할 수 있는 NPC가 없습니다.")
        return true
    end
    show_dialogue_node(entity, sid, npc_name, "start")
    return true
end)

hooks.on_action("1", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return false end
    local state = dialogue_states[entity]
    if not state then return false end
    local dlg = DIALOGUES[state.npc_name]
    if not dlg then dialogue_states[entity] = nil return false end
    local node = dlg.nodes[state.node_id]
    if not node then dialogue_states[entity] = nil return false end
    local choice = node.choices[1]
    if not choice then
        output:send(sid, "잘못된 선택입니다.")
        return true
    end
    execute_action(entity, sid, choice.action)
    if choice.next then
        show_dialogue_node(entity, sid, state.npc_name, choice.next)
    else
        dialogue_states[entity] = nil
        output:send(sid, colors.cyan .. "(대화 종료)" .. colors.reset)
    end
    return true
end)

hooks.on_action("2", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return false end
    local state = dialogue_states[entity]
    if not state then return false end
    local dlg = DIALOGUES[state.npc_name]
    if not dlg then dialogue_states[entity] = nil return false end
    local node = dlg.nodes[state.node_id]
    if not node then dialogue_states[entity] = nil return false end
    local choice = node.choices[2]
    if not choice then
        output:send(sid, "잘못된 선택입니다.")
        return true
    end
    execute_action(entity, sid, choice.action)
    if choice.next then
        show_dialogue_node(entity, sid, state.npc_name, choice.next)
    else
        dialogue_states[entity] = nil
        output:send(sid, colors.cyan .. "(대화 종료)" .. colors.reset)
    end
    return true
end)

hooks.on_action("3", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return false end
    local state = dialogue_states[entity]
    if not state then return false end
    local dlg = DIALOGUES[state.npc_name]
    if not dlg then dialogue_states[entity] = nil return false end
    local node = dlg.nodes[state.node_id]
    if not node then dialogue_states[entity] = nil return false end
    local choice = node.choices[3]
    if not choice then
        output:send(sid, "잘못된 선택입니다.")
        return true
    end
    execute_action(entity, sid, choice.action)
    if choice.next then
        show_dialogue_node(entity, sid, state.npc_name, choice.next)
    else
        dialogue_states[entity] = nil
        output:send(sid, colors.cyan .. "(대화 종료)" .. colors.reset)
    end
    return true
end)

hooks.on_action("4", function(ctx)
    local entity = ctx.entity
    local sid = sessions:session_for(entity)
    if not sid then return false end
    local state = dialogue_states[entity]
    if not state then return false end
    local dlg = DIALOGUES[state.npc_name]
    if not dlg then dialogue_states[entity] = nil return false end
    local node = dlg.nodes[state.node_id]
    if not node then dialogue_states[entity] = nil return false end
    local choice = node.choices[4]
    if not choice then
        output:send(sid, "잘못된 선택입니다.")
        return true
    end
    execute_action(entity, sid, choice.action)
    if choice.next then
        show_dialogue_node(entity, sid, state.npc_name, choice.next)
    else
        dialogue_states[entity] = nil
        output:send(sid, colors.cyan .. "(대화 종료)" .. colors.reset)
    end
    return true
end)

