use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::post,
    Json, Router,
};
use serde::{Deserialize, Serialize};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new().route("/generate", post(generate_dialogues_lua))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DialogueChoice {
    pub text: String,
    pub next: Option<String>,
    #[serde(default)]
    pub action: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DialogueNode {
    pub id: String,
    pub text: String,
    #[serde(default)]
    pub choices: Vec<DialogueChoice>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Dialogue {
    pub id: String,
    pub npc_name: String,
    #[serde(default)]
    pub nodes: Vec<DialogueNode>,
}

/// Called by generate_all.
pub fn generate_dialogues_lua_inner(state: &AppState) -> Result<String, String> {
    let content_dir = state.config.content_dir();
    let dialogues_path = content_dir.join("dialogues.json");
    let dialogues: Vec<Dialogue> = if dialogues_path.exists() {
        let text = std::fs::read_to_string(&dialogues_path).map_err(|e| format!("Read error: {e}"))?;
        serde_json::from_str(&text).unwrap_or_default()
    } else {
        vec![]
    };
    let lua = generate_lua(&dialogues);
    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }
    std::fs::write(scripts_dir.join("10_dialogues.lua"), &lua)
        .map_err(|e| format!("Failed to write: {e}"))?;
    Ok("scripts/10_dialogues.lua".to_string())
}

async fn generate_dialogues_lua(State(state): State<AppState>) -> impl IntoResponse {
    let content_dir = state.config.content_dir();
    let dialogues_path = content_dir.join("dialogues.json");

    let dialogues: Vec<Dialogue> = if dialogues_path.exists() {
        match std::fs::read_to_string(&dialogues_path) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_default(),
            Err(_) => vec![],
        }
    } else {
        vec![]
    };

    let lua = generate_lua(&dialogues);

    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }

    let path = scripts_dir.join("10_dialogues.lua");
    match std::fs::write(&path, &lua) {
        Ok(()) => (
            StatusCode::OK,
            Json(serde_json::json!({"ok": true, "path": "scripts/10_dialogues.lua", "preview": lua})),
        ),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"error": format!("Failed to write: {e}")})),
        ),
    }
}

fn escape_lua(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn generate_lua(dialogues: &[Dialogue]) -> String {
    let mut lua = String::new();
    lua.push_str("-- 10_dialogues.lua (auto-generated by MUD Game Maker)\n");
    lua.push_str("-- DO NOT EDIT MANUALLY -- changes will be overwritten\n\n");

    if dialogues.is_empty() {
        lua.push_str("-- No dialogues defined\n");
        return lua;
    }

    // Dialogue data table
    lua.push_str("local DIALOGUES = {\n");
    for d in dialogues {
        lua.push_str(&format!("    [\"{}\"] = {{\n", escape_lua(&d.npc_name)));
        lua.push_str(&format!("        id = \"{}\",\n", escape_lua(&d.id)));
        lua.push_str("        nodes = {\n");
        for node in &d.nodes {
            lua.push_str(&format!("            [\"{}\"] = {{\n", escape_lua(&node.id)));
            lua.push_str(&format!("                text = \"{}\",\n", escape_lua(&node.text)));
            lua.push_str("                choices = {\n");
            for choice in &node.choices {
                let next_str = match &choice.next {
                    Some(n) => format!("\"{}\"", escape_lua(n)),
                    None => "nil".to_string(),
                };
                let action_str = match &choice.action {
                    Some(a) => format!("\"{}\"", escape_lua(a)),
                    None => "nil".to_string(),
                };
                lua.push_str(&format!(
                    "                    {{ text = \"{}\", next = {}, action = {} }},\n",
                    escape_lua(&choice.text),
                    next_str,
                    action_str
                ));
            }
            lua.push_str("                },\n");
            lua.push_str("            },\n");
        }
        lua.push_str("        },\n");
        lua.push_str("    },\n");
    }
    lua.push_str("}\n\n");

    // Dialogue state tracking (entity → {npc_name, node_id})
    lua.push_str("local dialogue_states = {}\n\n");

    // Helper: show dialogue node
    lua.push_str("local function show_dialogue_node(entity, sid, npc_name, node_id)\n");
    lua.push_str("    local dlg = DIALOGUES[npc_name]\n");
    lua.push_str("    if not dlg then return false end\n");
    lua.push_str("    local node = dlg.nodes[node_id]\n");
    lua.push_str("    if not node then\n");
    lua.push_str("        dialogue_states[entity] = nil\n");
    lua.push_str("        return false\n");
    lua.push_str("    end\n");
    lua.push_str("    output:send(sid, \"\")\n");
    lua.push_str("    output:send(sid, colors.yellow .. npc_name .. colors.reset .. \": \" .. node.text)\n");
    lua.push_str("    if #node.choices > 0 then\n");
    lua.push_str("        for i, choice in ipairs(node.choices) do\n");
    lua.push_str("            output:send(sid, colors.cyan .. \"  \" .. i .. \". \" .. choice.text .. colors.reset)\n");
    lua.push_str("        end\n");
    lua.push_str("        dialogue_states[entity] = {npc_name = npc_name, node_id = node_id}\n");
    lua.push_str("    else\n");
    lua.push_str("        dialogue_states[entity] = nil\n");
    lua.push_str("    end\n");
    lua.push_str("    return true\n");
    lua.push_str("end\n\n");

    // Helper: execute choice action
    lua.push_str("local function execute_action(entity, sid, action_str)\n");
    lua.push_str("    if not action_str then return end\n");
    lua.push_str("    local cmd, arg = action_str:match(\"^(%w+):(.+)$\")\n");
    lua.push_str("    if not cmd then return end\n");
    lua.push_str("    if cmd == \"give_item\" then\n");
    lua.push_str("        local item = ecs:spawn()\n");
    lua.push_str("        ecs:set(item, \"Name\", arg)\n");
    lua.push_str("        ecs:set(item, \"ItemTag\", true)\n");
    lua.push_str("        ecs:set(item, \"Inventory\", entity)\n");
    lua.push_str("        output:send(sid, colors.green .. arg .. \"을(를) 받았습니다.\" .. colors.reset)\n");
    lua.push_str("    elseif cmd == \"give_gold\" then\n");
    lua.push_str("        local amount = tonumber(arg) or 0\n");
    lua.push_str("        local gold = ecs:get(entity, \"Gold\") or 0\n");
    lua.push_str("        ecs:set(entity, \"Gold\", gold + amount)\n");
    lua.push_str("        output:send(sid, colors.green .. amount .. \" 골드를 받았습니다.\" .. colors.reset)\n");
    lua.push_str("    elseif cmd == \"heal\" then\n");
    lua.push_str("        local hp = ecs:get(entity, \"Health\")\n");
    lua.push_str("        if hp then\n");
    lua.push_str("            hp.current = hp.max\n");
    lua.push_str("            ecs:set(entity, \"Health\", hp)\n");
    lua.push_str("            output:send(sid, colors.green .. \"체력이 완전히 회복되었습니다.\" .. colors.reset)\n");
    lua.push_str("        end\n");
    lua.push_str("    elseif cmd == \"start_quest\" then\n");
    lua.push_str("        -- Quest integration: set QuestLog component\n");
    lua.push_str("        local quest_log = ecs:get(entity, \"QuestLog\") or {active = {}, completed = {}}\n");
    lua.push_str("        if not quest_log.active[arg] and not quest_log.completed[arg] then\n");
    lua.push_str("            quest_log.active[arg] = {}\n");
    lua.push_str("            ecs:set(entity, \"QuestLog\", quest_log)\n");
    lua.push_str("            output:send(sid, colors.green .. \"퀘스트 '\" .. arg .. \"'을(를) 수락했습니다.\" .. colors.reset)\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("end\n\n");

    // talk command
    lua.push_str("hooks.on_action(\"talk\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    local target_name = ctx.args\n");
    lua.push_str("    local room = space:entity_room(entity)\n");
    lua.push_str("    if not room then return true end\n");
    lua.push_str("    -- Find NPC in room\n");
    lua.push_str("    local npc_name = nil\n");
    lua.push_str("    local occupants = space:room_occupants(room)\n");
    lua.push_str("    for _, occ in ipairs(occupants) do\n");
    lua.push_str("        if ecs:has(occ, \"NpcTag\") then\n");
    lua.push_str("            local name = ecs:get(occ, \"Name\") or \"\"\n");
    lua.push_str("            if target_name == \"\" or target_name == nil or name == target_name then\n");
    lua.push_str("                if DIALOGUES[name] then\n");
    lua.push_str("                    npc_name = name\n");
    lua.push_str("                    break\n");
    lua.push_str("                end\n");
    lua.push_str("            end\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    if not npc_name then\n");
    lua.push_str("        output:send(sid, \"대화할 수 있는 NPC가 없습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    show_dialogue_node(entity, sid, npc_name, \"start\")\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n\n");

    // Number choice handlers (1~4)
    for i in 1..=4 {
        lua.push_str(&format!("hooks.on_action(\"{}\", function(ctx)\n", i));
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    local sid = sessions:session_for(entity)\n");
        lua.push_str("    if not sid then return false end\n");
        lua.push_str("    local state = dialogue_states[entity]\n");
        lua.push_str("    if not state then return false end\n");
        lua.push_str("    local dlg = DIALOGUES[state.npc_name]\n");
        lua.push_str("    if not dlg then dialogue_states[entity] = nil return false end\n");
        lua.push_str("    local node = dlg.nodes[state.node_id]\n");
        lua.push_str("    if not node then dialogue_states[entity] = nil return false end\n");
        lua.push_str(&format!("    local choice = node.choices[{}]\n", i));
        lua.push_str("    if not choice then\n");
        lua.push_str("        output:send(sid, \"잘못된 선택입니다.\")\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    execute_action(entity, sid, choice.action)\n");
        lua.push_str("    if choice.next then\n");
        lua.push_str("        show_dialogue_node(entity, sid, state.npc_name, choice.next)\n");
        lua.push_str("    else\n");
        lua.push_str("        dialogue_states[entity] = nil\n");
        lua.push_str("        output:send(sid, colors.cyan .. \"(대화 종료)\" .. colors.reset)\n");
        lua.push_str("    end\n");
        lua.push_str("    return true\n");
        lua.push_str("end)\n\n");
    }

    lua
}
