use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::post,
    Json, Router,
};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new().route("/generate", post(generate_item_effects_lua))
}

/// Called by generate_all.
pub fn generate_item_effects_lua_inner(state: &AppState) -> Result<String, String> {
    let content_dir = state.config.content_dir();
    let items_path = content_dir.join("items.json");
    let items: Vec<serde_json::Value> = if items_path.exists() {
        let text = std::fs::read_to_string(&items_path).map_err(|e| format!("Read error: {e}"))?;
        serde_json::from_str(&text).unwrap_or_default()
    } else {
        vec![]
    };
    let lua = generate_lua(&items);
    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }
    std::fs::write(scripts_dir.join("08_item_effects.lua"), &lua)
        .map_err(|e| format!("Failed to write: {e}"))?;
    Ok("scripts/08_item_effects.lua".to_string())
}

async fn generate_item_effects_lua(State(state): State<AppState>) -> impl IntoResponse {
    let content_dir = state.config.content_dir();
    let items_path = content_dir.join("items.json");

    let items: Vec<serde_json::Value> = if items_path.exists() {
        match std::fs::read_to_string(&items_path) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_default(),
            Err(_) => vec![],
        }
    } else {
        vec![]
    };

    let lua = generate_lua(&items);

    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }

    let path = scripts_dir.join("08_item_effects.lua");
    match std::fs::write(&path, &lua) {
        Ok(()) => (
            StatusCode::OK,
            Json(serde_json::json!({"ok": true, "path": "scripts/08_item_effects.lua", "preview": lua})),
        ),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"error": format!("Failed to write: {e}")})),
        ),
    }
}

fn escape_lua(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn generate_lua(items: &[serde_json::Value]) -> String {
    let mut lua = String::new();
    lua.push_str("-- 08_item_effects.lua (auto-generated by MUD Game Maker)\n");
    lua.push_str("-- DO NOT EDIT MANUALLY -- changes will be overwritten\n\n");

    // Build item data table
    let consumables: Vec<&serde_json::Value> = items
        .iter()
        .filter(|i| i.get("item_type").and_then(|v| v.as_str()) == Some("consumable"))
        .collect();
    let weapons: Vec<&serde_json::Value> = items
        .iter()
        .filter(|i| i.get("item_type").and_then(|v| v.as_str()) == Some("weapon"))
        .collect();
    let armors: Vec<&serde_json::Value> = items
        .iter()
        .filter(|i| i.get("item_type").and_then(|v| v.as_str()) == Some("armor"))
        .collect();

    if consumables.is_empty() && weapons.is_empty() && armors.is_empty() {
        lua.push_str("-- No usable items defined\n");
        return lua;
    }

    // Item data lookup
    lua.push_str("local ITEM_DATA = {\n");
    for item in items {
        let id = item.get("id").and_then(|v| v.as_str()).unwrap_or("");
        let name = item.get("name").and_then(|v| v.as_str()).unwrap_or(id);
        let item_type = item.get("item_type").and_then(|v| v.as_str()).unwrap_or("");
        let heal = item.get("heal_amount").and_then(|v| v.as_i64()).unwrap_or(0);
        let atk = item.get("attack_bonus").and_then(|v| v.as_i64()).unwrap_or(0);
        let def = item.get("defense_bonus").and_then(|v| v.as_i64()).unwrap_or(0);
        let use_msg = item.get("use_message").and_then(|v| v.as_str()).unwrap_or("");
        let equip_slot = item.get("equip_slot").and_then(|v| v.as_str()).unwrap_or("");

        if item_type == "consumable" || item_type == "weapon" || item_type == "armor" {
            lua.push_str(&format!(
                "    [\"{}\"] = {{ item_type = \"{}\", heal_amount = {}, attack_bonus = {}, defense_bonus = {}, use_message = \"{}\", equip_slot = \"{}\" }},\n",
                escape_lua(name), escape_lua(item_type), heal, atk, def,
                escape_lua(use_msg), escape_lua(equip_slot)
            ));
        }
    }
    lua.push_str("}\n\n");

    // Helper: find item in inventory by name
    lua.push_str("local function find_inventory_item(entity, item_name)\n");
    lua.push_str("    local inv = ecs:get(entity, \"Inventory\")\n");
    lua.push_str("    if not inv or not inv.items then return nil end\n");
    lua.push_str("    for _, item_id in ipairs(inv.items) do\n");
    lua.push_str("        if ecs:get(item_id, \"Name\") == item_name then return item_id end\n");
    lua.push_str("    end\n");
    lua.push_str("    return nil\n");
    lua.push_str("end\n\n");

    // Helper: remove item from inventory
    lua.push_str("local function remove_from_inventory(entity, item_ent)\n");
    lua.push_str("    local inv = ecs:get(entity, \"Inventory\")\n");
    lua.push_str("    if not inv or not inv.items then return end\n");
    lua.push_str("    local new_items = {}\n");
    lua.push_str("    local removed = false\n");
    lua.push_str("    for _, id in ipairs(inv.items) do\n");
    lua.push_str("        if id == item_ent and not removed then\n");
    lua.push_str("            removed = true\n");
    lua.push_str("        else\n");
    lua.push_str("            table.insert(new_items, id)\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    ecs:set(entity, \"Inventory\", {items = new_items})\n");
    lua.push_str("end\n\n");

    // use command
    if !consumables.is_empty() {
        lua.push_str("-- Use consumable items\n");
        lua.push_str("hooks.on_action(\"use\", function(ctx)\n");
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    local item_name = ctx.args\n");
        lua.push_str("    if not item_name or item_name == \"\" then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"사용할 아이템을 지정하세요: use <아이템>\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local item_ent = find_inventory_item(entity, item_name)\n");
        lua.push_str("    if not item_ent then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"'\" .. item_name .. \"'을(를) 가지고 있지 않습니다.\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local data = ITEM_DATA[item_name]\n");
        lua.push_str("    if not data or data.item_type ~= \"consumable\" then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"'\" .. item_name .. \"'은(는) 사용할 수 없습니다.\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    -- Apply heal\n");
        lua.push_str("    if data.heal_amount > 0 then\n");
        lua.push_str("        local hp = ecs:get(entity, \"Health\")\n");
        lua.push_str("        if hp then\n");
        lua.push_str("            hp.current = math.min(hp.current + data.heal_amount, hp.max)\n");
        lua.push_str("            ecs:set(entity, \"Health\", hp)\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("    -- Remove item\n");
        lua.push_str("    remove_from_inventory(entity, item_ent)\n");
        lua.push_str("    ecs:despawn(item_ent)\n");
        lua.push_str("    local sid = sessions:session_for(entity)\n");
        lua.push_str("    if sid then\n");
        lua.push_str("        local msg = data.use_message ~= \"\" and data.use_message or (item_name .. \"을(를) 사용했습니다.\")\n");
        lua.push_str("        output:send(sid, msg)\n");
        lua.push_str("    end\n");
        lua.push_str("    return true\n");
        lua.push_str("end)\n\n");
    }

    // equip command
    if !weapons.is_empty() || !armors.is_empty() {
        lua.push_str("-- Equip items\n");
        lua.push_str("hooks.on_action(\"equip\", function(ctx)\n");
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    local item_name = ctx.args\n");
        lua.push_str("    if not item_name or item_name == \"\" then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"장착할 아이템을 지정하세요: equip <아이템>\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local item_ent = find_inventory_item(entity, item_name)\n");
        lua.push_str("    if not item_ent then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"'\" .. item_name .. \"'을(를) 가지고 있지 않습니다.\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local data = ITEM_DATA[item_name]\n");
        lua.push_str("    if not data or (data.item_type ~= \"weapon\" and data.item_type ~= \"armor\") then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"'\" .. item_name .. \"'은(는) 장착할 수 없습니다.\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    -- Apply bonuses\n");
        lua.push_str("    if data.attack_bonus > 0 then\n");
        lua.push_str("        local atk = ecs:get(entity, \"Attack\") or 0\n");
        lua.push_str("        ecs:set(entity, \"Attack\", atk + data.attack_bonus)\n");
        lua.push_str("    end\n");
        lua.push_str("    if data.defense_bonus > 0 then\n");
        lua.push_str("        local def = ecs:get(entity, \"Defense\") or 0\n");
        lua.push_str("        ecs:set(entity, \"Defense\", def + data.defense_bonus)\n");
        lua.push_str("    end\n");
        lua.push_str("    local sid = sessions:session_for(entity)\n");
        lua.push_str("    if sid then output:send(sid, item_name .. \"을(를) 장착했습니다.\") end\n");
        lua.push_str("    return true\n");
        lua.push_str("end)\n\n");

        // unequip command
        lua.push_str("-- Unequip items\n");
        lua.push_str("hooks.on_action(\"unequip\", function(ctx)\n");
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    local item_name = ctx.args\n");
        lua.push_str("    if not item_name or item_name == \"\" then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"해제할 아이템을 지정하세요: unequip <아이템>\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local item_ent = find_inventory_item(entity, item_name)\n");
        lua.push_str("    if not item_ent then\n");
        lua.push_str("        local sid = sessions:session_for(entity)\n");
        lua.push_str("        if sid then output:send(sid, \"'\" .. item_name .. \"'을(를) 가지고 있지 않습니다.\") end\n");
        lua.push_str("        return true\n");
        lua.push_str("    end\n");
        lua.push_str("    local data = ITEM_DATA[item_name]\n");
        lua.push_str("    if not data then return true end\n");
        lua.push_str("    -- Remove bonuses\n");
        lua.push_str("    if data.attack_bonus > 0 then\n");
        lua.push_str("        local atk = ecs:get(entity, \"Attack\") or 0\n");
        lua.push_str("        ecs:set(entity, \"Attack\", math.max(0, atk - data.attack_bonus))\n");
        lua.push_str("    end\n");
        lua.push_str("    if data.defense_bonus > 0 then\n");
        lua.push_str("        local def = ecs:get(entity, \"Defense\") or 0\n");
        lua.push_str("        ecs:set(entity, \"Defense\", math.max(0, def - data.defense_bonus))\n");
        lua.push_str("    end\n");
        lua.push_str("    local sid = sessions:session_for(entity)\n");
        lua.push_str("    if sid then output:send(sid, item_name .. \"을(를) 해제했습니다.\") end\n");
        lua.push_str("    return true\n");
        lua.push_str("end)\n");
    }

    lua
}
