use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::post,
    Json, Router,
};
use serde::{Deserialize, Serialize};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new().route("/generate", post(generate_quests_lua))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestObjective {
    #[serde(rename = "type")]
    pub obj_type: String,
    pub target: String,
    #[serde(default = "default_count")]
    pub count: u32,
}

fn default_count() -> u32 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestRewards {
    #[serde(default)]
    pub gold: u32,
    #[serde(default)]
    pub exp: u32,
    #[serde(default)]
    pub items: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Quest {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub npc_name: String,
    #[serde(default)]
    pub auto_complete: bool,
    #[serde(default)]
    pub objectives: Vec<QuestObjective>,
    #[serde(default)]
    pub rewards: QuestRewards,
}

impl Default for QuestRewards {
    fn default() -> Self {
        Self {
            gold: 0,
            exp: 0,
            items: vec![],
        }
    }
}

/// Called by generate_all.
pub fn generate_quests_lua_inner(state: &AppState) -> Result<String, String> {
    let content_dir = state.config.content_dir();
    let quests_path = content_dir.join("quests.json");
    let quests: Vec<Quest> = if quests_path.exists() {
        let text = std::fs::read_to_string(&quests_path).map_err(|e| format!("Read error: {e}"))?;
        serde_json::from_str(&text).unwrap_or_default()
    } else {
        vec![]
    };
    let lua = generate_lua(&quests);
    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }
    std::fs::write(scripts_dir.join("11_quests.lua"), &lua)
        .map_err(|e| format!("Failed to write: {e}"))?;
    Ok("scripts/11_quests.lua".to_string())
}

async fn generate_quests_lua(State(state): State<AppState>) -> impl IntoResponse {
    let content_dir = state.config.content_dir();
    let quests_path = content_dir.join("quests.json");

    let quests: Vec<Quest> = if quests_path.exists() {
        match std::fs::read_to_string(&quests_path) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_default(),
            Err(_) => vec![],
        }
    } else {
        vec![]
    };

    let lua = generate_lua(&quests);

    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }

    let path = scripts_dir.join("11_quests.lua");
    match std::fs::write(&path, &lua) {
        Ok(()) => (
            StatusCode::OK,
            Json(serde_json::json!({"ok": true, "path": "scripts/11_quests.lua", "preview": lua})),
        ),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"error": format!("Failed to write: {e}")})),
        ),
    }
}

fn escape_lua(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn generate_lua(quests: &[Quest]) -> String {
    let mut lua = String::new();
    lua.push_str("-- 11_quests.lua (auto-generated by MUD Game Maker)\n");
    lua.push_str("-- DO NOT EDIT MANUALLY -- changes will be overwritten\n\n");

    if quests.is_empty() {
        lua.push_str("-- No quests defined\n");
        return lua;
    }

    // Quest data table
    lua.push_str("local QUESTS = {\n");
    for q in quests {
        lua.push_str(&format!("    [\"{}\"] = {{\n", escape_lua(&q.id)));
        lua.push_str(&format!("        name = \"{}\",\n", escape_lua(&q.name)));
        lua.push_str(&format!("        description = \"{}\",\n", escape_lua(&q.description)));
        lua.push_str(&format!("        npc_name = \"{}\",\n", escape_lua(&q.npc_name)));
        lua.push_str(&format!("        auto_complete = {},\n", q.auto_complete));
        lua.push_str("        objectives = {\n");
        for obj in &q.objectives {
            lua.push_str(&format!(
                "            {{ type = \"{}\", target = \"{}\", count = {} }},\n",
                escape_lua(&obj.obj_type),
                escape_lua(&obj.target),
                obj.count
            ));
        }
        lua.push_str("        },\n");
        lua.push_str("        rewards = {\n");
        lua.push_str(&format!("            gold = {},\n", q.rewards.gold));
        lua.push_str(&format!("            exp = {},\n", q.rewards.exp));
        lua.push_str("            items = {");
        for (i, item) in q.rewards.items.iter().enumerate() {
            if i > 0 {
                lua.push_str(", ");
            }
            lua.push_str(&format!("\"{}\"", escape_lua(item)));
        }
        lua.push_str("},\n");
        lua.push_str("        },\n");
        lua.push_str("    },\n");
    }
    lua.push_str("}\n\n");

    // Helper: check if all objectives are complete
    lua.push_str("local function check_objectives_complete(quest_id, progress)\n");
    lua.push_str("    local quest = QUESTS[quest_id]\n");
    lua.push_str("    if not quest then return false end\n");
    lua.push_str("    for i, obj in ipairs(quest.objectives) do\n");
    lua.push_str("        local key = obj.type .. \":\" .. obj.target\n");
    lua.push_str("        local current = (progress and progress[key]) or 0\n");
    lua.push_str("        if current < obj.count then return false end\n");
    lua.push_str("    end\n");
    lua.push_str("    return true\n");
    lua.push_str("end\n\n");

    // Helper: give quest rewards
    lua.push_str("local function give_rewards(entity, sid, quest_id)\n");
    lua.push_str("    local quest = QUESTS[quest_id]\n");
    lua.push_str("    if not quest then return end\n");
    lua.push_str("    local r = quest.rewards\n");
    lua.push_str("    if r.gold > 0 then\n");
    lua.push_str("        local gold = ecs:get(entity, \"Gold\") or 0\n");
    lua.push_str("        ecs:set(entity, \"Gold\", gold + r.gold)\n");
    lua.push_str("    end\n");
    lua.push_str("    if r.exp > 0 then\n");
    lua.push_str("        local lvl = ecs:get(entity, \"Level\")\n");
    lua.push_str("        if lvl then\n");
    lua.push_str("            lvl.exp = (lvl.exp or 0) + r.exp\n");
    lua.push_str("            ecs:set(entity, \"Level\", lvl)\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    for _, item_name in ipairs(r.items) do\n");
    lua.push_str("        local item = ecs:spawn()\n");
    lua.push_str("        ecs:set(item, \"Name\", item_name)\n");
    lua.push_str("        ecs:set(item, \"ItemTag\", true)\n");
    lua.push_str("        ecs:set(item, \"Inventory\", entity)\n");
    lua.push_str("    end\n");
    lua.push_str("    -- Build reward message\n");
    lua.push_str("    local parts = {}\n");
    lua.push_str("    if r.gold > 0 then table.insert(parts, r.gold .. \" 골드\") end\n");
    lua.push_str("    if r.exp > 0 then table.insert(parts, r.exp .. \" 경험치\") end\n");
    lua.push_str("    for _, item_name in ipairs(r.items) do table.insert(parts, item_name) end\n");
    lua.push_str("    if sid and #parts > 0 then\n");
    lua.push_str("        output:send(sid, colors.green .. \"보상: \" .. table.concat(parts, \", \") .. colors.reset)\n");
    lua.push_str("    end\n");
    lua.push_str("end\n\n");

    // quest command — show quest log
    lua.push_str("hooks.on_action(\"quest\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    local ql = ecs:get(entity, \"QuestLog\") or {active = {}, completed = {}}\n");
    lua.push_str("    output:send(sid, colors.yellow .. \"=== 퀘스트 목록 ===\" .. colors.reset)\n");
    lua.push_str("    local has_active = false\n");
    lua.push_str("    for qid, progress in pairs(ql.active) do\n");
    lua.push_str("        has_active = true\n");
    lua.push_str("        local quest = QUESTS[qid]\n");
    lua.push_str("        if quest then\n");
    lua.push_str("            output:send(sid, colors.cyan .. \"[진행] \" .. quest.name .. colors.reset)\n");
    lua.push_str("            for _, obj in ipairs(quest.objectives) do\n");
    lua.push_str("                local key = obj.type .. \":\" .. obj.target\n");
    lua.push_str("                local current = (progress and progress[key]) or 0\n");
    lua.push_str("                local status_str = current >= obj.count and colors.green .. \"완료\" .. colors.reset or (current .. \"/\" .. obj.count)\n");
    lua.push_str("                output:send(sid, \"  - \" .. obj.target .. \" (\" .. status_str .. \")\")\n");
    lua.push_str("            end\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    if not has_active then\n");
    lua.push_str("        output:send(sid, \"  진행 중인 퀘스트가 없습니다.\")\n");
    lua.push_str("    end\n");
    lua.push_str("    local completed_count = 0\n");
    lua.push_str("    for _ in pairs(ql.completed) do completed_count = completed_count + 1 end\n");
    lua.push_str("    if completed_count > 0 then\n");
    lua.push_str("        output:send(sid, colors.green .. \"완료한 퀘스트: \" .. completed_count .. \"개\" .. colors.reset)\n");
    lua.push_str("    end\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n\n");

    // accept command
    lua.push_str("hooks.on_action(\"accept\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local quest_name = ctx.args\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    if not quest_name or quest_name == \"\" then\n");
    lua.push_str("        output:send(sid, \"수락할 퀘스트를 지정하세요: accept <퀘스트 이름>\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    -- Find quest by name\n");
    lua.push_str("    local quest_id = nil\n");
    lua.push_str("    for qid, q in pairs(QUESTS) do\n");
    lua.push_str("        if q.name == quest_name then quest_id = qid break end\n");
    lua.push_str("    end\n");
    lua.push_str("    if not quest_id then\n");
    lua.push_str("        output:send(sid, \"'\" .. quest_name .. \"' 퀘스트를 찾을 수 없습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local ql = ecs:get(entity, \"QuestLog\") or {active = {}, completed = {}}\n");
    lua.push_str("    if ql.active[quest_id] then\n");
    lua.push_str("        output:send(sid, \"이미 진행 중인 퀘스트입니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    if ql.completed[quest_id] then\n");
    lua.push_str("        output:send(sid, \"이미 완료한 퀘스트입니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    ql.active[quest_id] = {}\n");
    lua.push_str("    ecs:set(entity, \"QuestLog\", ql)\n");
    lua.push_str("    output:send(sid, colors.green .. \"퀘스트 '\" .. QUESTS[quest_id].name .. \"'을(를) 수락했습니다.\" .. colors.reset)\n");
    lua.push_str("    output:send(sid, QUESTS[quest_id].description)\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n\n");

    // on_tick: check kill objectives + auto-complete
    let has_kill = quests.iter().any(|q| q.objectives.iter().any(|o| o.obj_type == "kill"));
    if has_kill || quests.iter().any(|q| q.auto_complete) {
        lua.push_str("-- Tick: track kills and check quest completion\n");
        lua.push_str("hooks.on_tick(function(tick)\n");

        if has_kill {
            lua.push_str("    -- Track kills\n");
            lua.push_str("    local dead_entities = ecs:query(\"Dead\")\n");
            lua.push_str("    for _, dead_ent in ipairs(dead_entities) do\n");
            lua.push_str("        if ecs:has(dead_ent, \"NpcTag\") then\n");
            lua.push_str("            local dead_name = ecs:get(dead_ent, \"Name\") or \"\"\n");
            lua.push_str("            -- Update kill progress for all players\n");
            lua.push_str("            local players = ecs:query(\"PlayerTag\")\n");
            lua.push_str("            for _, player in ipairs(players) do\n");
            lua.push_str("                local ql = ecs:get(player, \"QuestLog\")\n");
            lua.push_str("                if ql and ql.active then\n");
            lua.push_str("                    local changed = false\n");
            lua.push_str("                    for qid, progress in pairs(ql.active) do\n");
            lua.push_str("                        local quest = QUESTS[qid]\n");
            lua.push_str("                        if quest then\n");
            lua.push_str("                            for _, obj in ipairs(quest.objectives) do\n");
            lua.push_str("                                if obj.type == \"kill\" and obj.target == dead_name then\n");
            lua.push_str("                                    local key = \"kill:\" .. dead_name\n");
            lua.push_str("                                    progress[key] = (progress[key] or 0) + 1\n");
            lua.push_str("                                    changed = true\n");
            lua.push_str("                                    local sid = sessions:session_for(player)\n");
            lua.push_str("                                    if sid then\n");
            lua.push_str("                                        output:send(sid, colors.cyan .. \"[퀘스트] \" .. dead_name .. \" 처치 (\" .. progress[key] .. \"/\" .. obj.count .. \")\" .. colors.reset)\n");
            lua.push_str("                                    end\n");
            lua.push_str("                                end\n");
            lua.push_str("                            end\n");
            lua.push_str("                        end\n");
            lua.push_str("                    end\n");
            lua.push_str("                    if changed then ecs:set(player, \"QuestLog\", ql) end\n");
            lua.push_str("                end\n");
            lua.push_str("            end\n");
            lua.push_str("        end\n");
            lua.push_str("    end\n\n");
        }

        lua.push_str("    -- Check auto-complete\n");
        lua.push_str("    local players = ecs:query(\"PlayerTag\")\n");
        lua.push_str("    for _, player in ipairs(players) do\n");
        lua.push_str("        local ql = ecs:get(player, \"QuestLog\")\n");
        lua.push_str("        if ql and ql.active then\n");
        lua.push_str("            local completed_ids = {}\n");
        lua.push_str("            for qid, progress in pairs(ql.active) do\n");
        lua.push_str("                local quest = QUESTS[qid]\n");
        lua.push_str("                if quest and quest.auto_complete and check_objectives_complete(qid, progress) then\n");
        lua.push_str("                    table.insert(completed_ids, qid)\n");
        lua.push_str("                end\n");
        lua.push_str("            end\n");
        lua.push_str("            for _, qid in ipairs(completed_ids) do\n");
        lua.push_str("                ql.active[qid] = nil\n");
        lua.push_str("                ql.completed[qid] = true\n");
        lua.push_str("                local sid = sessions:session_for(player)\n");
        lua.push_str("                if sid then\n");
        lua.push_str("                    output:send(sid, colors.yellow .. \"[퀘스트 완료] \" .. QUESTS[qid].name .. colors.reset)\n");
        lua.push_str("                end\n");
        lua.push_str("                give_rewards(player, sessions:session_for(player), qid)\n");
        lua.push_str("            end\n");
        lua.push_str("            if #completed_ids > 0 then ecs:set(player, \"QuestLog\", ql) end\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("end)\n\n");
    }

    // on_action "get": track collect objectives (item pickup)
    let has_collect = quests
        .iter()
        .any(|q| q.objectives.iter().any(|o| o.obj_type == "collect"));
    if has_collect {
        lua.push_str("-- Item pickup: track collect objectives\n");
        lua.push_str("hooks.on_action(\"get\", function(ctx)\n");
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    if not ecs:has(entity, \"PlayerTag\") then return false end\n");
        lua.push_str("    local item_name = ctx.args\n");
        lua.push_str("    if not item_name or item_name == \"\" then return false end\n");
        lua.push_str("    local ql = ecs:get(entity, \"QuestLog\")\n");
        lua.push_str("    if not ql or not ql.active then return false end\n");
        lua.push_str("    local changed = false\n");
        lua.push_str("    for qid, progress in pairs(ql.active) do\n");
        lua.push_str("        local quest = QUESTS[qid]\n");
        lua.push_str("        if quest then\n");
        lua.push_str("            for _, obj in ipairs(quest.objectives) do\n");
        lua.push_str("                if obj.type == \"collect\" and obj.target == item_name then\n");
        lua.push_str("                    local key = \"collect:\" .. item_name\n");
        lua.push_str("                    progress[key] = (progress[key] or 0) + 1\n");
        lua.push_str("                    changed = true\n");
        lua.push_str("                    local sid = sessions:session_for(entity)\n");
        lua.push_str("                    if sid then\n");
        lua.push_str("                        output:send(sid, colors.cyan .. \"[퀘스트] \" .. item_name .. \" 수집 (\" .. progress[key] .. \"/\" .. obj.count .. \")\" .. colors.reset)\n");
        lua.push_str("                    end\n");
        lua.push_str("                end\n");
        lua.push_str("            end\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("    if changed then ecs:set(entity, \"QuestLog\", ql) end\n");
        lua.push_str("    return false  -- do not consume the action, let the normal get handler run\n");
        lua.push_str("end)\n\n");
    }

    // on_action "talk": track talk objectives (NPC conversation)
    let has_talk = quests
        .iter()
        .any(|q| q.objectives.iter().any(|o| o.obj_type == "talk"));
    if has_talk {
        lua.push_str("-- NPC talk: track talk objectives\n");
        lua.push_str("hooks.on_action(\"talk\", function(ctx)\n");
        lua.push_str("    local entity = ctx.entity\n");
        lua.push_str("    if not ecs:has(entity, \"PlayerTag\") then return false end\n");
        lua.push_str("    local ql = ecs:get(entity, \"QuestLog\")\n");
        lua.push_str("    if not ql or not ql.active then return false end\n");
        lua.push_str("    -- Find NPC in room to get name\n");
        lua.push_str("    local room = space:entity_room(entity)\n");
        lua.push_str("    if not room then return false end\n");
        lua.push_str("    local occupants = space:room_occupants(room)\n");
        lua.push_str("    local npc_names = {}\n");
        lua.push_str("    for _, occ in ipairs(occupants) do\n");
        lua.push_str("        if ecs:has(occ, \"NpcTag\") then\n");
        lua.push_str("            local name = ecs:get(occ, \"Name\") or \"\"\n");
        lua.push_str("            npc_names[name] = true\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("    local changed = false\n");
        lua.push_str("    for qid, progress in pairs(ql.active) do\n");
        lua.push_str("        local quest = QUESTS[qid]\n");
        lua.push_str("        if quest then\n");
        lua.push_str("            for _, obj in ipairs(quest.objectives) do\n");
        lua.push_str("                if obj.type == \"talk\" and npc_names[obj.target] then\n");
        lua.push_str("                    local key = \"talk:\" .. obj.target\n");
        lua.push_str("                    if not progress[key] or progress[key] < 1 then\n");
        lua.push_str("                        progress[key] = 1\n");
        lua.push_str("                        changed = true\n");
        lua.push_str("                        local sid = sessions:session_for(entity)\n");
        lua.push_str("                        if sid then\n");
        lua.push_str("                            output:send(sid, colors.cyan .. \"[퀘스트] \" .. obj.target .. \"와(과) 대화 완료\" .. colors.reset)\n");
        lua.push_str("                        end\n");
        lua.push_str("                    end\n");
        lua.push_str("                end\n");
        lua.push_str("            end\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("    if changed then ecs:set(entity, \"QuestLog\", ql) end\n");
        lua.push_str("    return false  -- do not consume the action, let the dialogue system handle it\n");
        lua.push_str("end)\n\n");
    }

    // on_enter_room: visit objectives
    let has_visit = quests.iter().any(|q| q.objectives.iter().any(|o| o.obj_type == "visit"));
    if has_visit {
        lua.push_str("-- Room entry: track visit objectives\n");
        lua.push_str("hooks.on_enter_room(function(entity, room, old_room)\n");
        lua.push_str("    if not ecs:has(entity, \"PlayerTag\") then return end\n");
        lua.push_str("    local room_name = ecs:get(room, \"Name\") or \"\"\n");
        lua.push_str("    local ql = ecs:get(entity, \"QuestLog\")\n");
        lua.push_str("    if not ql or not ql.active then return end\n");
        lua.push_str("    local changed = false\n");
        lua.push_str("    for qid, progress in pairs(ql.active) do\n");
        lua.push_str("        local quest = QUESTS[qid]\n");
        lua.push_str("        if quest then\n");
        lua.push_str("            for _, obj in ipairs(quest.objectives) do\n");
        lua.push_str("                if obj.type == \"visit\" and obj.target == room_name then\n");
        lua.push_str("                    local key = \"visit:\" .. room_name\n");
        lua.push_str("                    if not progress[key] or progress[key] < obj.count then\n");
        lua.push_str("                        progress[key] = (progress[key] or 0) + 1\n");
        lua.push_str("                        changed = true\n");
        lua.push_str("                        local sid = sessions:session_for(entity)\n");
        lua.push_str("                        if sid then\n");
        lua.push_str("                            output:send(sid, colors.cyan .. \"[퀘스트] \" .. room_name .. \" 방문 완료\" .. colors.reset)\n");
        lua.push_str("                        end\n");
        lua.push_str("                    end\n");
        lua.push_str("                end\n");
        lua.push_str("            end\n");
        lua.push_str("        end\n");
        lua.push_str("    end\n");
        lua.push_str("    if changed then ecs:set(entity, \"QuestLog\", ql) end\n");
        lua.push_str("end)\n");
    }

    lua
}
