use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::post,
    Json, Router,
};
use serde::{Deserialize, Serialize};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new().route("/generate", post(generate_shops_lua))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopItem {
    pub item_id: String,
    #[serde(default)]
    pub price: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Shop {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub npc_name: String,
    #[serde(default)]
    pub room_name: String,
    #[serde(default)]
    pub items: Vec<ShopItem>,
    #[serde(default = "default_sell_rate")]
    pub sell_rate: f64,
}

fn default_sell_rate() -> f64 {
    0.5
}

/// Called by generate_all.
pub fn generate_shops_lua_inner(state: &AppState) -> Result<String, String> {
    let content_dir = state.config.content_dir();
    let shops_path = content_dir.join("shops.json");
    let shops: Vec<Shop> = if shops_path.exists() {
        let text = std::fs::read_to_string(&shops_path).map_err(|e| format!("Read error: {e}"))?;
        serde_json::from_str(&text).unwrap_or_default()
    } else {
        vec![]
    };
    let items_path = content_dir.join("items.json");
    let all_items: Vec<serde_json::Value> = if items_path.exists() {
        std::fs::read_to_string(&items_path)
            .ok()
            .and_then(|t| serde_json::from_str(&t).ok())
            .unwrap_or_default()
    } else {
        vec![]
    };
    let lua = generate_lua(&shops, &all_items);
    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }
    std::fs::write(scripts_dir.join("09_shops.lua"), &lua)
        .map_err(|e| format!("Failed to write: {e}"))?;
    Ok("scripts/09_shops.lua".to_string())
}

async fn generate_shops_lua(State(state): State<AppState>) -> impl IntoResponse {
    let content_dir = state.config.content_dir();
    let shops_path = content_dir.join("shops.json");

    let shops: Vec<Shop> = if shops_path.exists() {
        match std::fs::read_to_string(&shops_path) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_default(),
            Err(_) => vec![],
        }
    } else {
        vec![]
    };

    // Load item names for display
    let items_path = content_dir.join("items.json");
    let all_items: Vec<serde_json::Value> = if items_path.exists() {
        match std::fs::read_to_string(&items_path) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_default(),
            Err(_) => vec![],
        }
    } else {
        vec![]
    };

    let lua = generate_lua(&shops, &all_items);

    let scripts_dir = state.config.scripts_dir();
    if !scripts_dir.exists() {
        let _ = std::fs::create_dir_all(&scripts_dir);
    }

    let path = scripts_dir.join("09_shops.lua");
    match std::fs::write(&path, &lua) {
        Ok(()) => (
            StatusCode::OK,
            Json(serde_json::json!({"ok": true, "path": "scripts/09_shops.lua", "preview": lua})),
        ),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"error": format!("Failed to write: {e}")})),
        ),
    }
}

fn escape_lua(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn generate_lua(shops: &[Shop], all_items: &[serde_json::Value]) -> String {
    let mut lua = String::new();
    lua.push_str("-- 09_shops.lua (auto-generated by MUD Game Maker)\n");
    lua.push_str("-- DO NOT EDIT MANUALLY -- changes will be overwritten\n\n");

    if shops.is_empty() {
        lua.push_str("-- No shops defined\n");
        return lua;
    }

    // Shop data table
    lua.push_str("local SHOPS = {\n");
    for shop in shops {
        lua.push_str(&format!("    [\"{}\"] = {{\n", escape_lua(&shop.npc_name)));
        lua.push_str(&format!("        name = \"{}\",\n", escape_lua(&shop.name)));
        lua.push_str(&format!("        room = \"{}\",\n", escape_lua(&shop.room_name)));
        lua.push_str(&format!("        sell_rate = {},\n", shop.sell_rate));
        lua.push_str("        items = {\n");
        for si in &shop.items {
            // Resolve item name
            let item_name = all_items
                .iter()
                .find(|i| i.get("id").and_then(|v| v.as_str()) == Some(&si.item_id))
                .and_then(|i| i.get("name").and_then(|v| v.as_str()))
                .unwrap_or(&si.item_id);
            lua.push_str(&format!(
                "            {{ name = \"{}\", price = {} }},\n",
                escape_lua(item_name),
                si.price
            ));
        }
        lua.push_str("        },\n");
        lua.push_str("    },\n");
    }
    lua.push_str("}\n\n");

    // Find shop for current room's NPC
    lua.push_str("local function find_shop_in_room(entity)\n");
    lua.push_str("    local room = space:entity_room(entity)\n");
    lua.push_str("    if not room then return nil end\n");
    lua.push_str("    local occupants = space:room_occupants(room)\n");
    lua.push_str("    for _, occ in ipairs(occupants) do\n");
    lua.push_str("        if ecs:has(occ, \"NpcTag\") then\n");
    lua.push_str("            local npc_name = ecs:get(occ, \"Name\") or \"\"\n");
    lua.push_str("            if SHOPS[npc_name] then return SHOPS[npc_name], npc_name end\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    return nil\n");
    lua.push_str("end\n\n");

    // shop command
    lua.push_str("hooks.on_action(\"shop\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    local shop, npc_name = find_shop_in_room(entity)\n");
    lua.push_str("    if not shop then\n");
    lua.push_str("        output:send(sid, \"이 근처에 상점이 없습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    output:send(sid, colors.yellow .. \"=== \" .. shop.name .. \" (\" .. npc_name .. \") ===\" .. colors.reset)\n");
    lua.push_str("    for i, item in ipairs(shop.items) do\n");
    lua.push_str("        output:send(sid, string.format(\"  %d. %s - %d 골드\", i, item.name, item.price))\n");
    lua.push_str("    end\n");
    lua.push_str("    output:send(sid, colors.cyan .. \"구매: buy <아이템> | 판매: sell <아이템>\" .. colors.reset)\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n\n");

    // buy command
    lua.push_str("hooks.on_action(\"buy\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local item_name = ctx.args\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    if not item_name or item_name == \"\" then\n");
    lua.push_str("        output:send(sid, \"구매할 아이템을 지정하세요: buy <아이템>\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local shop = find_shop_in_room(entity)\n");
    lua.push_str("    if not shop then\n");
    lua.push_str("        output:send(sid, \"이 근처에 상점이 없습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local shop_item = nil\n");
    lua.push_str("    for _, si in ipairs(shop.items) do\n");
    lua.push_str("        if si.name == item_name then shop_item = si break end\n");
    lua.push_str("    end\n");
    lua.push_str("    if not shop_item then\n");
    lua.push_str("        output:send(sid, \"'\" .. item_name .. \"'은(는) 이 상점에서 판매하지 않습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local gold = ecs:get(entity, \"Gold\") or 0\n");
    lua.push_str("    if gold < shop_item.price then\n");
    lua.push_str("        output:send(sid, \"골드가 부족합니다. (보유: \" .. gold .. \", 필요: \" .. shop_item.price .. \")\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    -- Deduct gold\n");
    lua.push_str("    ecs:set(entity, \"Gold\", gold - shop_item.price)\n");
    lua.push_str("    -- Create item entity\n");
    lua.push_str("    local new_item = ecs:spawn()\n");
    lua.push_str("    ecs:set(new_item, \"Name\", shop_item.name)\n");
    lua.push_str("    ecs:set(new_item, \"ItemTag\", true)\n");
    lua.push_str("    ecs:set(new_item, \"Inventory\", entity)\n");
    lua.push_str("    output:send(sid, shop_item.name .. \"을(를) 구매했습니다. (-\" .. shop_item.price .. \" 골드)\")\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n\n");

    // sell command
    lua.push_str("hooks.on_action(\"sell\", function(ctx)\n");
    lua.push_str("    local entity = ctx.entity\n");
    lua.push_str("    local item_name = ctx.args\n");
    lua.push_str("    local sid = sessions:session_for(entity)\n");
    lua.push_str("    if not sid then return true end\n");
    lua.push_str("    if not item_name or item_name == \"\" then\n");
    lua.push_str("        output:send(sid, \"판매할 아이템을 지정하세요: sell <아이템>\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local shop = find_shop_in_room(entity)\n");
    lua.push_str("    if not shop then\n");
    lua.push_str("        output:send(sid, \"이 근처에 상점이 없습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    -- Find item in inventory\n");
    lua.push_str("    local inv = ecs:get(entity, \"Inventory\")\n");
    lua.push_str("    if not inv or not inv.items then\n");
    lua.push_str("        output:send(sid, \"인벤토리가 비어 있습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    local item_ent = nil\n");
    lua.push_str("    for _, id in ipairs(inv.items) do\n");
    lua.push_str("        if ecs:get(id, \"Name\") == item_name then item_ent = id break end\n");
    lua.push_str("    end\n");
    lua.push_str("    if not item_ent then\n");
    lua.push_str("        output:send(sid, \"'\" .. item_name .. \"'을(를) 가지고 있지 않습니다.\")\n");
    lua.push_str("        return true\n");
    lua.push_str("    end\n");
    lua.push_str("    -- Find sell price from shop items or use base value\n");
    lua.push_str("    local sell_price = 0\n");
    lua.push_str("    for _, si in ipairs(shop.items) do\n");
    lua.push_str("        if si.name == item_name then\n");
    lua.push_str("            sell_price = math.floor(si.price * shop.sell_rate)\n");
    lua.push_str("            break\n");
    lua.push_str("        end\n");
    lua.push_str("    end\n");
    lua.push_str("    if sell_price <= 0 then sell_price = 1 end\n");
    lua.push_str("    -- Remove item from inventory\n");
    lua.push_str("    local new_items = {}\n");
    lua.push_str("    local removed = false\n");
    lua.push_str("    for _, id in ipairs(inv.items) do\n");
    lua.push_str("        if id == item_ent and not removed then removed = true\n");
    lua.push_str("        else table.insert(new_items, id) end\n");
    lua.push_str("    end\n");
    lua.push_str("    ecs:set(entity, \"Inventory\", {items = new_items})\n");
    lua.push_str("    ecs:despawn(item_ent)\n");
    lua.push_str("    -- Add gold\n");
    lua.push_str("    local gold = ecs:get(entity, \"Gold\") or 0\n");
    lua.push_str("    ecs:set(entity, \"Gold\", gold + sell_price)\n");
    lua.push_str("    output:send(sid, item_name .. \"을(를) 판매했습니다. (+\" .. sell_price .. \" 골드)\")\n");
    lua.push_str("    return true\n");
    lua.push_str("end)\n");

    lua
}
